name: "drift"
version: "0.0.9"
usage: "Identifies configurations deviated from helm charts"
description: 'Identifies configurations deviated from helm charts, mostly due to inplace edits of kubernetes workload'
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helm-drift"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
